name: CMake CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            ninja-build \
            clang \
            clang-tidy

      - name: Configure
        run: |
          cmake -B build \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: |
          cmake --build build

      - name: Run tests
        run: |
          ctest --test-dir build --output-on-failure